name: Build and publish release

on:
  push:
    # Publish `$default-branch` as Docker `latest` image.
    branches:
      - $default-branch

    # Publish `v1.2.3` tags as releases.
    tags:
      - "v*.*.*"

jobs:
  build-apk:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.2"
          channel: "stable"

      - name: Fetch dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --split-per-abi

      - name: Publish to GitHub releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/app/outputs/apk/release/app-x86_64-release.apk
            build/app/outputs/apk/release/app-armeabi-v7a-release.apk
            build/app/outputs/apk/release/app-arm64-v8a-release.apk

#  build-windows:
#    runs-on: windows-latest
#    if: github.event_name == 'push'
#
#    permissions:
#      contents: write
#
#    steps:
#      - uses: actions/checkout@v3
#      - uses: subosito/flutter-action@v2
#        with:
#          flutter-version: "3.0.2"
#          channel: "stable"
#
#      - name: Fetch dependencies
#        run: flutter pub get
#
#      - name: Build Windows
#        run: flutter pub run msix:create
